# Generated by Django 2.2.6 on 2019-11-30 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191130_1138'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
