# Generated by Django 2.2.6 on 2020-04-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anchor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='主播名称')),
                ('room_id', models.IntegerField(verbose_name='房间号')),
                ('guild_id', models.IntegerField(verbose_name='公会号')),
                ('platform', models.CharField(max_length=50, verbose_name='平台名称')),
                ('value_at', models.CharField(max_length=255, verbose_name='获取时间')),
                ('follow', models.IntegerField(verbose_name='订阅数')),
                ('redu', models.IntegerField(verbose_name='热度')),
                ('section_id', models.IntegerField(verbose_name='版块ID')),
                ('last_kaibo_at', models.CharField(max_length=255, verbose_name='上次开播时间')),
                ('update_at', models.CharField(max_length=255, verbose_name='上次更新时间')),
                ('is_noguild', models.CharField(max_length=20, verbose_name='有无公会')),
                ('is_contact', models.CharField(max_length=20, verbose_name='是否联系过')),
                ('uid', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '主播',
                'verbose_name_plural': '主播',
            },
        ),
        migrations.CreateModel(
            name='AnchorGuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.IntegerField(verbose_name='主播ID')),
                ('guild_id', models.IntegerField(verbose_name='公会ID')),
                ('value_at', models.CharField(max_length=255, verbose_name='获取时间')),
            ],
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=30, verbose_name='')),
                ('platform', models.CharField(max_length=30, verbose_name='平台名称')),
                ('value_at', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=30, verbose_name='平台名称')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
            ],
        ),
    ]
