# Generated by Django 2.2.6 on 2020-04-11 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_content', models.CharField(default='', max_length=255, verbose_name='备注')),
                ('anchor_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anchor.Anchor')),
            ],
            options={
                'verbose_name': '备注',
                'verbose_name_plural': '备注',
            },
        ),
    ]
