# Generated by Django 2.2.6 on 2020-04-17 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anchor', '0004_anchor_room_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anchor',
            name='room_id',
            field=models.CharField(max_length=255, verbose_name='房间号'),
        ),
    ]
